import { program } from "commander";
import chalk from "chalk";
import { writeFileSync, readFileSync, existsSync } from "fs";
import { resolve } from "path";

// ─── Types ─────────────────────────────────────────────────────────────────

interface RspackRule {
  test: string;
  use?: string | { loader: string; options?: Record<string, unknown> };
  type?: string;
  exclude?: string;
  include?: string;
}

interface RspackPlugin {
  name: string;
  options?: Record<string, unknown>;
}

interface RspackOptimization {
  minimize?: boolean;
  splitChunks?: boolean;
  chunkIds?: string;
  moduleIds?: string;
  treeshaking?: boolean;
  sideEffects?: boolean;
}

interface RspackDevServer {
  port?: number;
  host?: string;
  hot?: boolean;
  open?: boolean;
  proxy?: Record<string, unknown>;
  historyApiFallback?: boolean;
  compress?: boolean;
}

interface RspackOutput {
  path?: string;
  filename?: string;
  chunkFilename?: string;
  publicPath?: string;
  clean?: boolean;
  libraryType?: string;
}

interface RspackResolve {
  extensions?: string;
  alias?: Record<string, unknown>;
  modules?: string;
  mainFields?: string;
}

interface RspackConfig {
  entry?: Record<string, string>;
  output?: Partial<RspackOutput>;
  module?: { rules: RspackRule[] };
  plugins?: RspackPlugin[];
  optimization?: Partial<RspackOptimization>;
  devServer?: Partial<RspackDevServer>;
  resolve?: Partial<RspackResolve>;
  [key: string]: unknown;
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function loadConfig(filePath: string): RspackConfig {
  if (!existsSync(filePath)) {
    console.error(chalk.red(`✗ Config file not found: ${filePath}`));
    process.exit(1);
  }
  const raw = readFileSync(filePath, "utf8");
  // Extract JSON from JS module export for simple manipulation
  const match = raw.match(/\/\*\s*__RSPACK_CONFIG_JSON__\s*([\s\S]+?)\s*__END__\s*\*\//);
  if (match) {
    return JSON.parse(match[1].trim()) as RspackConfig;
  }
  console.error(chalk.red(`✗ Cannot parse config (must be generated by this CLI)`));
  process.exit(1);
}

function saveConfig(filePath: string, config: RspackConfig): void {
  const json = JSON.stringify(config, null, 2);
  const js = generateJsFromConfig(config, json);
  writeFileSync(filePath, js, "utf8");
}

function generateJsFromConfig(config: RspackConfig, json: string): string {
  const pluginLines = (config.plugins ?? []).map((p) => {
    const opts = p.options ? `, ${JSON.stringify(p.options)}` : "";
    const known: Record<string, string> = {
      HtmlRspackPlugin: `new rspack.HtmlRspackPlugin(${opts ? JSON.stringify(p.options, null, 4) : "{}"})`,
      CopyRspackPlugin: `new rspack.CopyRspackPlugin(${opts ? JSON.stringify(p.options, null, 4) : "{ patterns: [] }"})`,
      DefinePlugin: `new rspack.DefinePlugin(${p.options ? JSON.stringify(p.options, null, 4) : "{}"})`,
      MiniCssExtractPlugin: `new rspack.CssExtractRspackPlugin(${p.options ? JSON.stringify(p.options, null, 4) : "{}"})`,
    };
    return `    ${known[p.name] ?? `/* ${p.name} - configure manually */`}`;
  });

  const ruleLines = (config.module?.rules ?? []).map((r) => {
    const useStr =
      typeof r.use === "string"
        ? `"${r.use}"`
        : r.use
        ? JSON.stringify(r.use, null, 6)
        : "undefined";
    return `    {
      test: ${r.test},${r.exclude ? `\n      exclude: ${r.exclude},` : ""}${r.include ? `\n      include: ${r.include},` : ""}
      use: ${useStr},${r.type ? `\n      type: "${r.type}",` : ""}
    }`;
  });

  return `/* __RSPACK_CONFIG_JSON__
${json}
__END__ */
import { rspack } from "@rspack/core";

export default {
  entry: ${JSON.stringify(config.entry ?? { main: "./src/index.ts" }, null, 4)},

  output: ${JSON.stringify(config.output ?? {}, null, 4)},

  module: {
    rules: [
${ruleLines.join(",\n")}
    ],
  },

  plugins: [
${pluginLines.join(",\n")}
  ],

  optimization: ${JSON.stringify(config.optimization ?? {}, null, 4)},

  devServer: ${JSON.stringify(config.devServer ?? {}, null, 4)},

  resolve: ${JSON.stringify(config.resolve ?? {}, null, 4)},
};
`;
}

// ─── Default config ────────────────────────────────────────────────────────

function defaultConfig(): RspackConfig {
  return {
    entry: { main: "./src/index.ts" },
    output: {
      filename: "[name].[contenthash].js",
      chunkFilename: "[name].[contenthash].chunk.js",
      path: "./dist",
      clean: true,
      publicPath: "auto",
    },
    module: {
      rules: [
        {
          test: "/\\.(ts|tsx|js|jsx)$/",
          use: {
            loader: "builtin:swc-loader",
            options: {
              jsc: { parser: { syntax: "typescript", tsx: true } },
            },
          },
          exclude: "/node_modules/",
        },
        {
          test: "/\\.css$/",
          use: "css-loader",
          type: "javascript/auto",
        },
      ],
    },
    plugins: [
      { name: "HtmlRspackPlugin", options: { template: "./public/index.html" } },
    ],
    optimization: {},
    devServer: {
      port: 3000,
      hot: true,
    },
    resolve: {
      extensions: [".ts", ".tsx", ".js", ".jsx", ".json"] as unknown as string,
    },
  };
}

// ─── CLI ───────────────────────────────────────────────────────────────────

program
  .name("rspack-config")
  .description(chalk.bold("Rspack bundler configuration generator CLI"))
  .version("1.0.0");

// ── init ──────────────────────────────────────────────────────────────────

program
  .command("init")
  .description("Generate starter rspack.config.js with entry, output, TypeScript/CSS loaders, HTML plugin")
  .option("-o, --output <path>", "Output path", "rspack.config.js")
  .option("-f, --force", "Overwrite existing file", false)
  .action((opts: { output: string; force: boolean }) => {
    const outPath = resolve(process.cwd(), opts.output);
    if (existsSync(outPath) && !opts.force) {
      console.error(chalk.red(`✗ File already exists: ${opts.output}`));
      console.error(chalk.dim("  Use --force to overwrite."));
      process.exit(1);
    }
    const config = defaultConfig();
    saveConfig(outPath, config);
    console.log(chalk.green(`✔ Created ${opts.output}`));
    console.log();
    console.log(chalk.bold("Next steps:"));
    console.log(`  ${chalk.cyan("npm install -D @rspack/core @rspack/cli")}`);
    console.log(`  ${chalk.cyan("npx rspack serve")}  ${chalk.dim("# dev server")}`);
    console.log(`  ${chalk.cyan("npx rspack build")}  ${chalk.dim("# production build")}`);
    console.log();
    console.log(chalk.dim("Docs: https://rspack.dev/guide/start/quick-start"));
  });

// ── add-loader ─────────────────────────────────────────────────────────────

program
  .command("add-loader <ext>")
  .description("Add a module rule for a file extension")
  .option("-c, --config <file>", "Config file path", "rspack.config.js")
  .option("--test <regex>", "Regex test pattern (e.g. /\\.scss$/)")
  .option("--use <loader>", "Loader name (e.g. sass-loader)")
  .option("--options <json>", "Loader options as JSON")
  .option("--exclude <pattern>", "Exclude pattern (e.g. /node_modules/)")
  .option("--include <pattern>", "Include pattern")
  .option("--type <type>", "Asset module type (e.g. asset/resource)")
  .action(
    (
      ext: string,
      opts: {
        config: string;
        test?: string;
        use?: string;
        options?: string;
        exclude?: string;
        include?: string;
        type?: string;
      }
    ) => {
      const filePath = resolve(process.cwd(), opts.config);
      const config = loadConfig(filePath);
      if (!config.module) config.module = { rules: [] };

      const loaderOptions = opts.options ? JSON.parse(opts.options) as Record<string, unknown> : undefined;
      const testPattern = opts.test ?? `/\\.${ext}$/`;

      const rule: RspackRule = {
        test: testPattern,
        ...(opts.exclude && { exclude: opts.exclude }),
        ...(opts.include && { include: opts.include }),
        ...(opts.use && {
          use: loaderOptions
            ? { loader: opts.use, options: loaderOptions }
            : opts.use,
        }),
        ...(opts.type && { type: opts.type }),
      };

      config.module.rules.push(rule);
      saveConfig(filePath, config);

      console.log(chalk.green(`✔ Added rule for .${ext} files`));
      console.log(chalk.dim(`  test: ${testPattern}`));
      if (opts.use) console.log(chalk.dim(`  use: ${opts.use}`));
      if (opts.type) console.log(chalk.dim(`  type: ${opts.type}`));
    }
  );

// ── add-plugin ─────────────────────────────────────────────────────────────

program
  .command("add-plugin <name>")
  .description("Add a plugin (HtmlRspackPlugin, CopyRspackPlugin, DefinePlugin, MiniCssExtractPlugin)")
  .option("-c, --config <file>", "Config file path", "rspack.config.js")
  .option("--name <name>", "Plugin name")
  .option("--options <json>", "Plugin options as JSON")
  .action(
    (
      name: string,
      opts: { config: string; name?: string; options?: string }
    ) => {
      const filePath = resolve(process.cwd(), opts.config);
      const config = loadConfig(filePath);
      if (!config.plugins) config.plugins = [];

      const pluginName = opts.name ?? name;
      const pluginOptions = opts.options ? JSON.parse(opts.options) as Record<string, unknown> : undefined;

      const supported = ["HtmlRspackPlugin", "CopyRspackPlugin", "DefinePlugin", "MiniCssExtractPlugin"];
      if (!supported.includes(pluginName)) {
        console.error(chalk.yellow(`⚠ Unknown plugin: ${pluginName}`));
        console.error(chalk.dim(`  Supported: ${supported.join(", ")}`));
      }

      config.plugins.push({ name: pluginName, options: pluginOptions });
      saveConfig(filePath, config);

      console.log(chalk.green(`✔ Added plugin: ${pluginName}`));
      if (pluginOptions) console.log(chalk.dim(`  options: ${JSON.stringify(pluginOptions)}`));
    }
  );

// ── set-optimization ────────────────────────────────────────────────────────

program
  .command("set-optimization")
  .description("Configure optimization settings")
  .option("-c, --config <file>", "Config file path", "rspack.config.js")
  .option("--minimize <bool>", "Enable minimization (true/false)")
  .option("--split-chunks <bool>", "Enable splitChunks (true/false)")
  .option("--chunk-ids <mode>", "Chunk IDs mode: named, deterministic")
  .option("--module-ids <mode>", "Module IDs mode: named, deterministic, hashed")
  .option("--tree-shaking <bool>", "Enable tree shaking (true/false)")
  .option("--side-effects <bool>", "Respect sideEffects flag (true/false)")
  .action(
    (opts: {
      config: string;
      minimize?: string;
      splitChunks?: string;
      chunkIds?: string;
      moduleIds?: string;
      treeshaking?: string;
      sideEffects?: string;
    }) => {
      const filePath = resolve(process.cwd(), opts.config);
      const config = loadConfig(filePath);
      if (!config.optimization) config.optimization = {};

      const parseBool = (v: string | undefined): boolean | undefined =>
        v === "true" ? true : v === "false" ? false : undefined;

      if (opts.minimize !== undefined) config.optimization.minimize = parseBool(opts.minimize);
      if (opts.splitChunks !== undefined) config.optimization.splitChunks = parseBool(opts.splitChunks);
      if (opts.chunkIds) config.optimization.chunkIds = opts.chunkIds;
      if (opts.moduleIds) config.optimization.moduleIds = opts.moduleIds;
      if (opts.treeshaking !== undefined) config.optimization.treeshaking = parseBool(opts.treeshaking);
      if (opts.sideEffects !== undefined) config.optimization.sideEffects = parseBool(opts.sideEffects);

      saveConfig(filePath, config);
      console.log(chalk.green("✔ Optimization updated"));
      console.log(chalk.dim(`  ${JSON.stringify(config.optimization, null, 2)}`));
    }
  );

// ── set-devserver ───────────────────────────────────────────────────────────

program
  .command("set-devserver")
  .description("Configure dev server settings")
  .option("-c, --config <file>", "Config file path", "rspack.config.js")
  .option("--port <number>", "Dev server port")
  .option("--host <host>", "Dev server host")
  .option("--hot <bool>", "Enable HMR (true/false)")
  .option("--open <bool>", "Open browser on start (true/false)")
  .option("--proxy <json>", "Proxy configuration as JSON")
  .option("--history-api-fallback <bool>", "Enable history API fallback (true/false)")
  .option("--compress <bool>", "Enable gzip compression (true/false)")
  .action(
    (opts: {
      config: string;
      port?: string;
      host?: string;
      hot?: string;
      open?: string;
      proxy?: string;
      historyApiFallback?: string;
      compress?: string;
    }) => {
      const filePath = resolve(process.cwd(), opts.config);
      const config = loadConfig(filePath);
      if (!config.devServer) config.devServer = {};

      const parseBool = (v: string | undefined): boolean | undefined =>
        v === "true" ? true : v === "false" ? false : undefined;

      if (opts.port) config.devServer.port = parseInt(opts.port, 10);
      if (opts.host) config.devServer.host = opts.host;
      if (opts.hot !== undefined) config.devServer.hot = parseBool(opts.hot);
      if (opts.open !== undefined) config.devServer.open = parseBool(opts.open);
      if (opts.proxy) config.devServer.proxy = JSON.parse(opts.proxy) as Record<string, unknown>;
      if (opts.historyApiFallback !== undefined)
        config.devServer.historyApiFallback = parseBool(opts.historyApiFallback);
      if (opts.compress !== undefined) config.devServer.compress = parseBool(opts.compress);

      saveConfig(filePath, config);
      console.log(chalk.green("✔ DevServer updated"));
      console.log(chalk.dim(`  ${JSON.stringify(config.devServer, null, 2)}`));
    }
  );

// ── set-output ──────────────────────────────────────────────────────────────

program
  .command("set-output")
  .description("Configure output settings")
  .option("-c, --config <file>", "Config file path", "rspack.config.js")
  .option("--path <path>", "Output directory path")
  .option("--filename <name>", "Output filename pattern")
  .option("--chunk-filename <name>", "Chunk filename pattern")
  .option("--public-path <path>", "Public path for assets")
  .option("--clean <bool>", "Clean output directory before build")
  .option("--library-type <type>", "Library type: var, module, commonjs, umd")
  .action(
    (opts: {
      config: string;
      path?: string;
      filename?: string;
      chunkFilename?: string;
      publicPath?: string;
      clean?: string;
      libraryType?: string;
    }) => {
      const filePath = resolve(process.cwd(), opts.config);
      const config = loadConfig(filePath);
      if (!config.output) config.output = {};

      const parseBool = (v: string | undefined): boolean | undefined =>
        v === "true" ? true : v === "false" ? false : undefined;

      if (opts.path) config.output.path = opts.path;
      if (opts.filename) config.output.filename = opts.filename;
      if (opts.chunkFilename) config.output.chunkFilename = opts.chunkFilename;
      if (opts.publicPath) config.output.publicPath = opts.publicPath;
      if (opts.clean !== undefined) config.output.clean = parseBool(opts.clean);
      if (opts.libraryType) config.output.libraryType = opts.libraryType;

      saveConfig(filePath, config);
      console.log(chalk.green("✔ Output updated"));
      console.log(chalk.dim(`  ${JSON.stringify(config.output, null, 2)}`));
    }
  );

// ── set-resolve ─────────────────────────────────────────────────────────────

program
  .command("set-resolve")
  .description("Configure resolve settings")
  .option("-c, --config <file>", "Config file path", "rspack.config.js")
  .option("--extensions <list>", "Comma-separated extensions (e.g. .ts,.js,.json)")
  .option("--alias <json>", "Alias map as JSON (e.g. {\"@\":\"./src\"})")
  .option("--modules <list>", "Comma-separated module directories (e.g. node_modules,src)")
  .option("--main-fields <list>", "Comma-separated main fields (e.g. browser,module,main)")
  .action(
    (opts: {
      config: string;
      extensions?: string;
      alias?: string;
      modules?: string;
      mainFields?: string;
    }) => {
      const filePath = resolve(process.cwd(), opts.config);
      const config = loadConfig(filePath);
      if (!config.resolve) config.resolve = {};

      if (opts.extensions) config.resolve.extensions = opts.extensions as string;
      if (opts.alias) config.resolve.alias = JSON.parse(opts.alias) as Record<string, unknown>;
      if (opts.modules) config.resolve.modules = opts.modules;
      if (opts.mainFields) config.resolve.mainFields = opts.mainFields;

      saveConfig(filePath, config);
      console.log(chalk.green("✔ Resolve updated"));
      console.log(chalk.dim(`  ${JSON.stringify(config.resolve, null, 2)}`));
    }
  );

// ── validate ────────────────────────────────────────────────────────────────

program
  .command("validate [file]")
  .description("Validate rspack config structure")
  .action((file = "rspack.config.js") => {
    const filePath = resolve(process.cwd(), file);
    if (!existsSync(filePath)) {
      console.error(chalk.red(`✗ File not found: ${file}`));
      process.exit(1);
    }

    const config = loadConfig(filePath);
    const errors: string[] = [];
    const warnings: string[] = [];

    // Validate entry
    if (!config.entry || Object.keys(config.entry).length === 0) {
      errors.push("entry is missing or empty");
    }

    // Validate output
    if (!config.output) {
      warnings.push("output is not configured (will use defaults)");
    } else {
      if (!config.output.path) warnings.push("output.path is not set");
      if (!config.output.filename) warnings.push("output.filename is not set");
    }

    // Validate module rules
    if (config.module?.rules) {
      config.module.rules.forEach((rule, i) => {
        if (!rule.test) errors.push(`module.rules[${i}] is missing test pattern`);
        if (!rule.use && !rule.type) warnings.push(`module.rules[${i}] has no use or type`);
      });
    }

    // Validate plugins
    if (config.plugins) {
      const supported = ["HtmlRspackPlugin", "CopyRspackPlugin", "DefinePlugin", "MiniCssExtractPlugin"];
      config.plugins.forEach((p) => {
        if (!supported.includes(p.name)) {
          warnings.push(`plugin "${p.name}" is not a known built-in Rspack plugin`);
        }
      });
    }

    // Validate devServer
    if (config.devServer?.port) {
      const port = config.devServer.port;
      if (port < 1 || port > 65535) errors.push(`devServer.port ${port} is out of range (1-65535)`);
    }

    // Summary
    if (errors.length === 0 && warnings.length === 0) {
      console.log(chalk.green(`✔ ${file} is valid`));
      return;
    }

    if (errors.length > 0) {
      console.log(chalk.red(`✗ Validation failed: ${file}`));
      errors.forEach((e) => console.log(chalk.red(`  • ${e}`)));
    }

    if (warnings.length > 0) {
      console.log(chalk.yellow(`⚠ Warnings:`));
      warnings.forEach((w) => console.log(chalk.yellow(`  • ${w}`)));
    }

    if (errors.length > 0) process.exit(1);
  });

// ── show ────────────────────────────────────────────────────────────────────

program
  .command("show [file]")
  .description("Display formatted config summary")
  .action((file = "rspack.config.js") => {
    const filePath = resolve(process.cwd(), file);
    const config = loadConfig(filePath);

    const sep = chalk.dim("─".repeat(50));

    console.log();
    console.log(chalk.bold.cyan(`  📦 Rspack Config: ${file}`));
    console.log(sep);

    // Entry
    console.log(chalk.bold("  Entry:"));
    Object.entries(config.entry ?? {}).forEach(([k, v]) => {
      console.log(`    ${chalk.green(k)} → ${chalk.dim(v)}`);
    });

    // Output
    console.log(chalk.bold("\n  Output:"));
    const out = config.output ?? {};
    console.log(`    path:        ${chalk.dim(String(out.path ?? "(default)"))}`);
    console.log(`    filename:    ${chalk.dim(String(out.filename ?? "(default)"))}`);
    if (out.chunkFilename) console.log(`    chunk:       ${chalk.dim(out.chunkFilename)}`);
    if (out.publicPath) console.log(`    publicPath:  ${chalk.dim(out.publicPath)}`);
    if (out.clean !== undefined) console.log(`    clean:       ${chalk.dim(String(out.clean))}`);

    // Module rules
    const rules = config.module?.rules ?? [];
    console.log(chalk.bold(`\n  Module Rules (${rules.length}):`));
    rules.forEach((r, i) => {
      const useStr = typeof r.use === "string" ? r.use : r.use?.loader ?? r.type ?? "(none)";
      console.log(`    [${i}] test: ${chalk.yellow(r.test)} → ${chalk.green(useStr)}`);
    });

    // Plugins
    const plugins = config.plugins ?? [];
    console.log(chalk.bold(`\n  Plugins (${plugins.length}):`));
    plugins.forEach((p) => {
      console.log(`    • ${chalk.cyan(p.name)}${p.options ? chalk.dim(" " + JSON.stringify(p.options)) : ""}`);
    });

    // Optimization
    const opt = config.optimization ?? {};
    if (Object.keys(opt).length > 0) {
      console.log(chalk.bold("\n  Optimization:"));
      Object.entries(opt).forEach(([k, v]) => {
        console.log(`    ${k}: ${chalk.dim(JSON.stringify(v))}`);
      });
    }

    // DevServer
    const ds = config.devServer ?? {};
    if (Object.keys(ds).length > 0) {
      console.log(chalk.bold("\n  DevServer:"));
      Object.entries(ds).forEach(([k, v]) => {
        console.log(`    ${k}: ${chalk.dim(JSON.stringify(v))}`);
      });
    }

    // Resolve
    const res = config.resolve ?? {};
    if (Object.keys(res).length > 0) {
      console.log(chalk.bold("\n  Resolve:"));
      if (res.extensions) console.log(`    extensions: ${chalk.dim(JSON.stringify(res.extensions))}`);
      if (res.alias) console.log(`    alias: ${chalk.dim(JSON.stringify(res.alias))}`);
      if (res.modules) console.log(`    modules: ${chalk.dim(res.modules)}`);
    }

    console.log(sep);
    console.log();
  });

program.parse(process.argv);
